version: 2
jobs:
  build:
    docker:
      - image: cimg/go:1.1
    working_directory: /go/src/github.com/nomical/terraform-provider-ecxfabric
    steps:
      - checkout
      - run:
          name: Vet code
          command: |
            make vet
      - run:
          name: Run unit tests
          command: |
            make test

  terraform-acceptance-tests:
    docker:
      - image: cimg/go:1.18
    working_directory: /go/src/github.com/nomical/terraform-provider-ecxfabric
    steps:
      - checkout
      - run:
          name: Run acceptance tests
          command: |
            make testacc
          no_output_timeout: 30m

  compile-and-release:
    docker:
      - image: circleci/golang:1.15.5
    working_directory: /go/src/github.com/nomical/terraform-provider-ecxfabric
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: |
            go get -u github.com/tcnksm/ghr
            go get -u github.com/mitchellh/gox
      - run:
          name: Cross compile & release to GitHub
          command: |
            chmod +x scripts/build-releases.sh
            scripts/build-releases.sh "dist/" $CIRCLE_TAG
            ghr -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -replace $CIRCLE_TAG dist/
workflows:
  version: 2
  all:
    jobs:
      - build:
          filters: # required since `deploy` has tag filters AND requires `build`
            tags:
              only: /.*/
      # - terraform-acceptance-tests:
      #     requires:
      #       - build
      #     filters:  # required since `deploy` has tag filters AND requires `build`
      #       tags:
      #         only: /.*/
      - compile-and-release:
          requires:
            - build
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
